---
title: "Recommendation Model"
author: "Jack Hickey"
date: "2/2/2022"
output: html_document
---

Basic Movie Recommendation System
```{r}
#read in the data
links <- read.csv("ml-latest-small/links.csv")
movies <- read.csv("ml-latest-small/movies.csv")
ratings <- read.csv("ml-latest-small/ratings.csv")
tags <- read.csv("ml-latest-small/tags.csv")
```

```{r}
library(reshape2)
library(stringi)
```

```{r}
#create ratings matrix from userID and movie ID
ratingmat <- dcast(ratings, userId~movieId, value.var = "rating", na.rm=FALSE)
#now remove the userID so we have a movie ratings ID matrix
ratingmat <- as.matrix(ratingmat[,-1])
```


```{r}
library(recommenderlab)
#reduce the size of the ratings matrix
ratingmat <- as(ratingmat, "realRatingMatrix")

ratingmat <- normalize(ratingmat)

rec_mod <- Recommender(ratingmat, method = "UBCF", param = list(method = "Cosine", nn = 10))
```


```{r}
library(dplyr)
#obtain some predictions
Top_5_pred <- predict(rec_mod, ratingmat[1], n = 5) #pred for first user
Top_5_List <- as(Top_5_pred,"list")
#show 5 predictions, note: these will be in movie ID number
Top_5_List 

#create dataframe of the recommneded movieID numbers
Top_5_df = data.frame(Top_5_List)
colnames(Top_5_df) <- "movieId"

str(Top_5_df)
Top_5_df$movieId <- as.integer(Top_5_df$movieId)
Top_5_df$movieId <- as.numeric(levels(Top_5_df$movieId))

names <- left_join(Top_5_df, movies, by = "movieId")
names
```


```{r}
```


```{r}
```


```{r}
```

